services:
  kim:
    image: ghcr.io/kingshot-project/kingshot-discord-bot:v1.4.1
    container_name: kim-kingshot-discord-bot
    volumes:
      - {{mount_folder}}/kim/db:/app/db
    restart: unless-stopped
    environment:
      - DISCORD_BOT_TOKEN={{KIM_TOKEN}}
      - UPDATE=0
      - TZ=UTC
  rad:
    image: ghcr.io/kingshot-project/kingshot-discord-bot:v1.4.1
    container_name: rad-kingshot-discord-bot
    volumes:
      - {{mount_folder}}/rad/db:/app/db
    restart: unless-stopped
    environment:
      - DISCORD_BOT_TOKEN={{RAD_TOKEN}}
      - UPDATE=0
      - TZ=UTC